### ISSUE TITLE
Inotify not detect delete file or directory.

### ISSUE THREAD

**Issue by RatneshFlash** [cooltronics/NFC_device#2]
When I create file in monitor folder.
-> It start monitoring directory.
-> After created file when I delete file, program not able to detect it.

ToDo;
Implement folder delete condition in InotifyLoop().

**Comment by appuSandy** [comment]
@Ratnesh69 
-> deleting a file using rm command is will be detected as IN_DELETE, but when we delete using GUI of linux or window will just move a file to trash so it will be detected as IN_MOVE.
-> have Implemented folder/file delete condition in InotifyLoop().
