### ISSUE TITLE
Put comment from where I call any function to send data to nfc

### ISSUE THREAD

**Issue by RatneshFlash** [cooltronics/NFC_device#3]
-> I am not able to find from where I can call sendToNfc() routine. 
this routine will convert file in to ndef format.

ToDo:
-> Define specific line from where I can call sendToNfc() function. And put FIXME or some comment there.
-> Function name sendToNfc() is just for example.

**Comment by RatneshFlash** [comment]
I check code and follow this steps.
-> run nfc application for watching share directory.
-> Now create file in share folder by mouse right click.
-> Rename file.
-> Open file and edit some text.
-> Now by press CTRL + S program detect was **Move to/from** in     if (event->mask & IN_MOVE) line operation in program.

It seem that move to/from is routine from where we can call sendNfc() routine.
Also check Which line is there when we file from c program.
-> open file.
-> write some text.
-> close file.

**Comment by appuSandy** [comment]
@Ratnesh69  
-> No need of checking IN_MOVE event as when using a C program which is already in FileAPI lib.
--> just need to call sendToNfc() function when IN_CLOSE is triggered.
-->  Need to add below line to in inotifyLoop funcion.
                           if (event->mask & IN_CLOSE)
                {
                    if (event->mask & IN_ISDIR)
                    {
                        cout << "The directory " << event->name
                                << " was IN_CLOSE.\n" << endl;
                    }
                    else
                    {
                                         sendToNfc()
                    cout << "The file " << event->name
                            << "was IN_CLOSE" << event->wd << endl;
                    }
                } ''
